[project]
name = "rag-evaluation-with-ragas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Suman Sarkar", email = "ssarkar445@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.9",
    "datasets>=5.0.1",
    "langchain>=1.4.0",
    "langchain-chroma>=1.1.0",
    "langchain-openai>=1.6.2",
    "langchain-text-splitters>=1.1.2",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
rag-evaluation-with-ragas = "rag_evaluation_with_ragas:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"